### ISSUE TITLE
How could I cluster my error data without any querys?

### ISSUE THREAD

**Issue by ACbccc** [slymane/vlslice#10]
Thanks for your great work !  I want to use vlslice to cluster my error pics for object detection, But I dont know what dimensions like "CEO" or "People" should I use as querys. could I cluster my error data without any querys?

**Comment by slymane** [comment]
Hello! This project was built to support auditing vision-language models without any labeled data. It does not support investigating vision models on specific labeled tasks (e.g., object detection).

I do think you might be able to hack it into working for your use case, though.

You can find where we store the delta c metric (which captures the vision-language relationship) here:
https://github.com/slymane/vlslice/blob/main/vlslice/server/server.py#L85

You might try modifying this code to instead load the errors for your object detection task. To avoid breaking things, you'll need to scale those errors to the range [-1, +1]. The errors should align with the topk images selected on line 80. If everything works, you should get clusters based on image similarity and similarity in error with all our tooling working (and a "query" bar, which doesn't really do anything). Let me know how it goes if you try this!
