### ISSUE TITLE
Add new data source for demo images and embeddings

### ISSUE THREAD

**Issue by slymane** [slymane/vlslice#5]
Due to ongoing cost accrual, we recently spun down the AWS resources hosting the demo images and embeddings. This results in a broken download link when following the quick start instructions in the README. To fix this, we need to:

- [ ] Update the demo Numpy arrays to point to local files
- [ ] Provide a compressed image folder containing the corresponding images

Users can then download the images and embeddings locally without using hosted resources.

**Comment by tikboaHIT** [comment]
I was just wondering if there have been any updates？

**Comment by slymane** [comment]
> I was just wondering if there have been any updates？

This got put on delay between me catching covid and the holidays. I'll be looking into it today!

**Comment by slymane** [comment]
Resolved! You can find updated steps in the README. 

Unfortunately, moving images from a CDN to local files leads to significant slowdowns in image display when using the built-in Flask server. **I've added the "Faster Image Loading" section in the README to walk through setting up a more sophisticated server that allows images to be loaded nearly instantly as a mitigation.** The original simple version should be fine for just poking around VLSlice, but I recommend making these changes for any serious use.
