### ISSUE TITLE
Unable to link" wget https://d30mxw38m32j53.cloudfront.net/embeddings/imgs_dev.npy -O vlslice/server/data/imgs.npy"

### ISSUE THREAD

**Issue by meng8407** [slymane/vlslice#6]
Are there any special linking requirements for downloading sample data and models? I accessed this URL through a proxy server;
"wget https://d30mxw38m32j53.cloudfront.net/embeddings/imgs_dev.npy -O vlslice/server/data/imgs.npy"
![01c5115e69f60ffba4ad35067068f96](https://github.com/slymane/vlslice/assets/69879311/7279e728-bd6d-42b6-a665-f386a21ca0da)

**Comment by slymane** [comment]
Please see #5.
