### ISSUE TITLE
I have other questions that I would like to ask you to answer. I have my own picture data. How can I build these "imgs.npy","lbls.npy","embs.npy", three files with my own picture data?

### ISSUE THREAD

**Issue by meng8407** [slymane/vlslice#9]
1.imgs.npy, is the path to your image data, right?
2.lbls.py，Is this a description of the text that corresponds to each picture?
3.embs.npy,Is each image data vectorized using CLIP model?
Looking forward you early repaly!

**Comment by meng8407** [comment]
2.lbls.py，Is this a description of the text that corresponds to each picture
3.embs.npy,Is each image data vectorized using CLIP model.
Looking forward you early replay!

**Comment by slymane** [comment]
This can be done following [Using Your Own Data](https://github.com/slymane/vlslice?tab=readme-ov-file#using-your-own-data) and [Using Your Own Model](https://github.com/slymane/vlslice?tab=readme-ov-file#using-your-own-model).

`imgs.npy` is the path to your image data. Note that this will need to be in the `static/` folder to serve with flask, or whatever folder was specified for nginx if following the [Faster Image Loading](https://github.com/slymane/vlslice?tab=readme-ov-file#faster-image-loading) guide (highly recommended for local images). If your images are hosted online, you can also specify URLs (e.g., `https://mydomain.com/image-xxxx.jpg)`.

`lbls.npy` is a text description or "label" of each image. This is just used to exclude certain classes of images from display in the [config.yml](https://github.com/slymane/vlslice/blob/main/vlslice/server/config.yml) and can be filled with dummy strings if you don't have labels available. For example, we use it to exclude subparts of larger entities.

`embs.npy` is the CLIP embedding for each image (or as you say, the vectorized data). We use `openai/clip-vit-base-patch16` from Hugging Face but this can be trivially changed to other CLIP versions, or even to other ViL models if following the steps in  [Using Your Own Model](https://github.com/slymane/vlslice?tab=readme-ov-file#using-your-own-model).

**Comment by meng8407** [comment]
> [这可以按照使用您自己的数据](https://github.com/slymane/vlslice?tab=readme-ov-file#using-your-own-data)和[使用您自己的模型](https://github.com/slymane/vlslice?tab=readme-ov-file#using-your-own-model)来完成。
> 
> `imgs.npy`是图像数据的路径。[请注意，如果遵循更快的图像加载](https://github.com/slymane/vlslice?tab=readme-ov-file#faster-image-loading)指南（强烈建议用于本地图像），则这需要位于`static/`与 Flask 一起使用的文件夹中，或者为 nginx 指定的任何文件夹中。如果您的图像在线托管，您还可以指定 URL（例如.[](https://github.com/slymane/vlslice?tab=readme-ov-file#faster-image-loading)`https://mydomain.com/image-xxxx.jpg)`
> 
> `lbls.npy`是每个图像的文本描述或“标签”。这仅用于从[config.yml](https://github.com/slymane/vlslice/blob/main/vlslice/server/config.yml)中的显示中排除某些类别的图像。例如，我们用它来排除较大实体的子部分。`null`可以通过在配置中指定来省略此文件。
> 
> `embs.npy`是每个图像的 CLIP 嵌入（或者如您所说，矢量化数据）。我们使用Hugging Face，但如果按照[使用您自己的模型](https://github.com/slymane/vlslice?tab=readme-ov-file#using-your-own-model)`openai/clip-vit-base-patch16`中的步骤操作，则可以轻松更改为其他 CLIP 版本，甚至更改为其他 ViL 模型 。[](https://github.com/slymane/vlslice?tab=readme-ov-file#using-your-own-model)

Thank you very much for your answer, and I will consult you if I have any other questions。

**Comment by slymane** [comment]
Happy to help!
